### ISSUE TITLE
ImportError: cannot import name 'get_installed_distributions'

### ISSUE THREAD

**Issue by kazishariar** [achillesrasquinha/pipupgrade#1]
Error: pipupgrade                                                                                                                                                                  
Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 7, in <module>
    from pipupgrade.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/pipupgrade/__main__.py", line 5, in <module>
    from pipupgrade.commands import command as main
  File "/usr/local/lib/python3.6/site-packages/pipupgrade/commands/__init__.py", line 4, in <module>
    from pipupgrade import _pip
  File "/usr/local/lib/python3.6/site-packages/pipupgrade/_pip.py", line 7, in <module>
    from pip import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions'

**Comment by achillesrasquinha** [comment]
pip version?

**Comment by kazishariar** [comment]
Pipv.10, osx

**Comment by achillesrasquinha** [comment]
Hi @kazishariar, had it fixed and released for 0.1.1. Please update

```
$ pip install --upgrade pipupgrade
```

Let me know if it persists!

**Comment by kazishariar** [comment]
This is related^^

**Comment by achillesrasquinha** [comment]
@kshntn @kazishariar Looks more like 2.7 issue for me rn. I'll confirm when I have this fixed.

**Comment by achillesrasquinha** [comment]
Hi @kshntn @kazishariar 

Had some fixes released for 0.2.0. Let me know if that fixes for y'all both. Again, to update:

```
$ pip install --no-cache --upgrade pipupgrade
```

**Comment by kazishariar** [comment]
Fixed.

**Comment by kshntn** [comment]
Hi,
still not working for me
Do you wish to update 116 packages? [Y/n]: y
Traceback (most recent call last):
  File "/usr/local/bin/pipupgrade", line 11, in <module>
    load_entry_point('pipupgrade==0.2.0', 'console_scripts', 'pipupgrade')()
  File "/usr/local/lib/python2.7/dist-packages/pipupgrade/commands/__init__.py", line 16, in command
    if args.yes or cli.confirm(query):
  File "/usr/local/lib/python2.7/dist-packages/pipupgrade/cli.py", line 12, in confirm
    output = input(query)
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by achillesrasquinha** [comment]
Hi @kshntn, what Python version are you using? I am unable to replicate your issue.

**Comment by achillesrasquinha** [comment]
@kshntn Fixed with 0.2.3! Sorry about this.

Let me know after upgrading if it works for you. Let's close this issue once done.

**Comment by kshntn** [comment]
It worked..  but no files got updated..
I got below error
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/pip-req-tracker-aqEMW_/59731abbf87b764da5ecee3dadde740b1fba2edd1fc12ce52e415788'

**Comment by achillesrasquinha** [comment]
Closing this due to inactivity.

**Comment by kshntn** [comment]
Hii.. I am sorry.. missed the mail.. It working now!!
