### ISSUE TITLE
Stuck at "Checking..." forever

### ISSUE THREAD

**Issue by achillesrasquinha** [achillesrasquinha/pipupgrade#30]
`pipupgrade` uses `pip` to check for outdated packages (`pip list --outdated`) to be precise. This causes `pip` to enter into an infinite loop for some reason ([pip issue](https://github.com/pypa/pip/issues/3532)).

If you're on macOS, try deleting the pip cache.

```
$ rm -rf ~/Library/Caches/pip
```

else

```
$ rm -rf ~/.cache/pip
```

**Comment by pradyunsg** [comment]
This should've been fixed in newer releases of pip. We've switched to doing things differently w.r.t. this cache management.

**Comment by achillesrasquinha** [comment]
@pradyunsg Thanks for the update! Would this project be helpful in anyway to the core `pip` package? Would be open to send in a PR if so.

**Comment by baterflyrity** [comment]
This bug has not been resolved. The problem is still presented in lates Windows+Python environment.
