### ISSUE TITLE
ValueError with _exhaustive_wait with all commands

### ISSUE THREAD

**Issue by RashiqAzhan** [achillesrasquinha/pipupgrade#95]
#### What's the bug all about?

The upgrade doesn't carry out. It never finishes execution and gets stuck. I have tried reinstalling both the package and python itself but to no avail.

#### What command led to this issue?

```
$ "pipupgrade"
```

#### Logs

*Please paste the logs using `pipupgrade --verbose`*

```
2021-02-01 14:28:38,410 | INFO | Environment: {'version': '1.8.2', 'python_version': '3.10.0a4', 'os': 'Windows-10-10.0.19041-SP0', 'config': {'path': {'BASE': 'c:\\python310\\lib\\site-packages\\pipupgrade', 'DATA': 'c:\\python310\\lib\\site-packages\\pipupgrade\\data', 'CACHE': 'C:\\Users\\user\\.config\\pipupgrade'}}, 'settings': {'settings': {'version': '1.8.0', 'cache_timeout': '86400', 'jobs': '64'}}}
2021-02-01 14:28:38,411 | INFO | Arguments Passed: {'args': (), 'kwargs': {'ARGUMENTS': <class 'inspect._empty'>, 'packages': [], 'ignore': None, 'pip_path': None, 'yes': 0, 'check': 0, 'upgrade_type': ['minor', 'patch'], 'latest': 0, 'format': 'table', 'all': 0, 'pip': 0, 'self': False, 'requirements': None, 'pipfile': None, 'interactive': 0, 'project': None, 'git_username': None, 'git_email': None, 'pull_request': False, 'github_access_token': None, 'github_reponame': None, 'github_username': None, 'target_branch': 'master', 'jobs': 64, 'user': 0, 'no_included_requirements': 0, 'no_cache': 0, 'output': None, 'ignore_error': 0, 'force': 0, 'no_color': 0, 'verbose': True}, 'a': <pipupgrade.to_params.<locals>.O object at 0x0000022B5208A430>}
Checking...
2021-02-01 14:28:38,414 | INFO | `pip` executables found: ['C:\\Python310\\Scripts\\pip.EXE', 'C:\\Python310\\Scripts\\pip3.EXE']
2021-02-01 14:28:38,415 | INFO | Using 64 jobs...
Exception in thread Thread-1 (_handle_workers):
Traceback (most recent call last):
  File "c:\python310\lib\threading.py", line 972, in _bootstrap_inner
2021-02-01 14:28:40,319 | INFO | Fetching installed packages for C:\Python310\Scripts\pip.EXE...
2021-02-01 14:28:40,319 | INFO | Fetching installed packages for C:\Python310\Scripts\pip3.EXE...
2021-02-01 14:28:40,320 | INFO | Executing command: C:\Python310\Scripts\pip.EXE list --outdated --format json
2021-02-01 14:28:40,320 | INFO | Executing command: C:\Python310\Scripts\pip3.EXE list --outdated --format json
    self.run()
  File "c:\python310\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python310\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\python310\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
2021-02-01 14:28:44,327 | INFO | 23 packages found for C:\Python310\Scripts\pip3.EXE.
2021-02-01 14:28:44,366 | INFO | 23 packages found for C:\Python310\Scripts\pip.EXE.
Exception in thread Thread-3 (_handle_workers):
2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'cachetools', 'version': '4.1.1', 'latest_version': '4.2.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'certifi', 'version': '2020.11.8', 'latest_version': '2020.12.5', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'google-api-python-client', 'version': '1.7.11', 'latest_version': '1.12.8', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'google-auth', 'version': '1.23.0', 'latest_version': '1.24.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'idna', 'version': '2.10', 'latest_version': '3.1', 'late2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'lazy-object-proxy', 'version': '1.4.3', 'latest_version'2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'isort', 'version': '5.6.4', 'latest_version': '5.7.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,666 | INFO | Initializing Package {'name': 'packaging', 'version': '20.8', 'latest_version': '20.9',2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'Faker', 'version': '4.18.0', 'latest_version': '5.8.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
22021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'fonttools', 'version': '4.18.0', 'latest_version': '4.19.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'google-auth-oauthlib', 'version': '0.4.0', 'latest_version': '0.4.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
st_filetype': 'wheel'} of type <class 'dict'>...
: '1.5.2', 'latest_filetype': 'sdist'} of type <class 'dict'>...
2Traceback (most recent call last):
 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,665 | INFO | Initializing Package {'name': 'chardet', 'version': '3.0.4', 'latest_version': '4.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
021-02-01 14:28:47,667 | INFO | Fetching package cachetools information from DB...
22021-02-01 14:28:47,669 | INFO | Fetching package Faker information from DB...
22021-02-01 14:28:47,670 | INFO | Fetching package fonttools information from DB...
2021-02-01 14:28:47,671 | INFO | Fetching package google-auth-oauthlib information from DB...
021-02-01 14:28:47,668 | INFO | Fetching package google-auth information from DB...
2021-02-01 14:28:47,671 | INFO | Fetching package idna information from DB...
2021-02-01 14:28:47,672 | INFO | Fetching package lazy-object-proxy information from DB...
2  File "c:\python310\lib\threading.py", line 972, in _bootstrap_inner
2021-02-01 14:28:47,667 | INFO | Fetching package certifi information from DB...
2021-02-01 14:28:47,676 | INFO | Initializing Package {'name': 'psutil', 'version': '5.7.3', 'latest_version': '5.8.0', 'latest_filetype': 'sdist'} of type <class 'dict'>...
2021-02-01 14:28:47,674 | INFO | Initializing Package {'name': 'pip', 'version': '20.3.3', 'latest_version': '21.0.1', '2021-02-01 14:28:47,675 | INFO | Initializing Package {'name': 'pipupgrade', 'version': '1.8.2', 'latest_version': '1.8.021-02-01 14:28:47,669 | INFO | Fetching package isort information from DB...
2021-02-01 14:28:47,675 | INFO | Initializing Package {'name': 'pipx', 'version': '0.15.6.0', 'latest_version': '0.16.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,676 | INFO | Initializing Package {'name': 'protobuf', 'version': '3.9.2', 'latest_version': '3.14.02021-02-01 14:28:47,673 | INFO | Fetching package chardet information from DB...
2021-02-01 14:28:47,676 | INFO | Initializing Package {'name': 'requests', 'version': '2.25.0', 'latest_version': '2.25.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,677 | INFO | Initializing Package {'name': 'rsa', 'version': '4.6', 'latest_version': '4.7', 'latest_filetype': 'wheel'} of type <class 'dict'>...

latest_filetype': 'wheel'} of type <class 'dict'>...
4', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,678 | INFO | Fetching package psutil information from DB...
', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,678 | INFO | Initializing Package {'name': 'setuptools', 'version': '51.0.0', 'latest_version': '53.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
    self.run()
021-02-01 14:28:47,668 | INFO | Fetching package google-api-python-client information from DB...
2021-02-01 14:28:47,680 | INFO | Initializing Package {'name': 'urllib3', 'version': '1.24.2', 'latest_version': '1.26.3', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:47,680 = to_datetime(res["_updated_at"]) + timedelta(seconds = cache_timeout)
  File "c:\python310\lib\site-packages\pipupgrade\model\package.py", line 69, in to_datetime', 'latest_version': '1.4.2'
  File "c:\python310\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    return datetime.strptime(string, "%Y-%m-%d %H:%M:%S.%f")nformation from DB...
TypeError: strptime() argument 1 must be str, not datetime.datetimeation from DB...
"""tiprocessing.pool.RemoteTraceback:
222021-02-01 14:28:47,682 | INFO | Initializing Package {'name': 'virtualenv', 'version': '20.2.2', 'latest_version': '2The above exception was the direct cause of the following exception:
2  File "c:\python310\lib\threading.py", line 910, in run
Traceback (most recent call last):etching package pip information from DB...
  File "c:\python310\lib\multiprocessing\pool.py", line 125, in workerfrom DB...
    result = (True, func(*args, **kwds))g package userpath information from DB...
  File "c:\python310\lib\site-packages\pipupgrade\commands\helper.py", line 331, in get_registry_from_pip
    registry     = Registry(source = pip_path, packages = packages,rom DB...
  File "c:\python310\lib\site-packages\pipupgrade\model\registry.py", line 111, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):om DB...
  File "c:\python310\lib\multiprocessing\pool.py", line 870, in nextn from DB...
    raise value8:47,685 | INFO | Fetching package virtualenv information from DB...
TypeError: strptime() argument 1 must be str, not datetime.datetime
"""tiprocessing.pool.RemoteTraceback:
"""
The above exception was the direct cause of the following exception:
    wait(sentinels, timeout=timeout)sing\pool.py", line 125, in worker
  File "c:\python310\lib\multiprocessing\pool.py", line 519, in _handle_workers
Traceback (most recent call last):kwds))
  File "c:\python310\lib\site-packages\pipupgrade\commands\__init__.py", line 75, in command
    return _command(**ARGUMENTS)_wait_for_updates(current_sentinels, change_notifier)
  File "c:\python310\lib\site-packages\pipupgrade\commands\__init__.py", line 197, in _command
  File "c:\python310\lib\multiprocessing\connection.py", line 884, in wait
    for registry in pool.imap_unordered(
  File "c:\python310\lib\multiprocessing\pool.py", line 870, in next
    raise value
TypeError: strptime() argument 1 must be str, not datetime.datetime
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)

  File "c:\python310\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
An error occured while performing the above command. This could be an issue with
"pipupgrade". Kindly post an issue at https://github.com/achillesrasquinha/pipupgrade/issues
Exception in thread Thread-3 (_handle_workers):
2021-02-01 14:28:48,848 | INFO | Initializing Package {'name': 'chardet', 'version': '3.0.4', 'latest_version': '4.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,848 | INFO | Initializing Package {'name': 'certifi', 'version': '2020.11.8', 'latest_version': '2020.12.5', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,849 | INFO | Initializing Package {'name': 'google-api-python-client', 'version': '1.7.11', 'latest_version': '1.12.8', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,848 | INFO | Initializing Package {'name': 'Faker', 'version': '4.18.0', 'latest_version': '5.8.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,849 | INFO | Initializing Package {'name': 'lazy-object-proxy', 'version': '1.4.3', 'latest_version'2021-02-01 14:28:48,848 | INFO | Initializing Package {'name': 'cachetools', 'version': '4.1.1', 'latest_version': '4.2.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,849 | INFO | Initializing Package {'name': 'idna', 'version': '2.10', 'latest_version': '3.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,849 | INFO | Initializing Package {'name': 'fonttools', 'version': '4.18.0', 'latest_version': '4.19.1', 'latest_filetype': 'wheel'} of type <class 'dict'>...
Traceback (most recent call last):
22021-02-01 14:28:48,849 | INFO | Initializing Package {'name': 'google-auth-oauthlib', 'version': '0.4.0', 'latest_versi2021-02-01 14:28:48,851 | INFO | Fetching package google-api-python-client information from DB...
2021-02-01 14:28:48,849 | INFO | Initializing Package {'name': 'google-auth', 'version': '1.23.0', 'latest_version': '1.22021-02-01 14:28:48,849 | INFO | Initializing Package {'name': 'isort', 'version': '5.6.4', 'latest_version': '5.7.0', '222021-02-01 14:28:48,851 | INFO | Fetching package certifi information from DB...
2021-02-01 14:28:48,853 | INFO | Fetching package fonttools information from DB...
on': '0.4.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
  File "c:\python310\lib\threading.py", line 972, in _bootstrap_inner
: '1.5.2', 'latest_filetype': 'sdist'} of type <class 'dict'>...
24.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
021-02-01 14:28:48,852 | INFO | Fetching package Faker information from DB...
latest_filetype': 'wheel'} of type <class 'dict'>...
021-02-01 14:28:48,852 | INFO | Fetching package cachetools information from DB...
021-02-01 14:28:48,851 | INFO | Fetching package chardet information from DB...
021-02-01 14:28:48,852 | INFO | Fetching package idna information from DB...
2021-02-01 14:28:48,855 | INFO | Initializing Package {'name': 'packaging', 'version': '20.8', 'latest_version': '20.9', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,856 | INFO | Fetching package lazy-object-proxy information from DB...
2021-02-01 14:28:48,857 | INFO | Initializing Package {'name': 'pip', 'version': '20.3.3', 'latest_version': '21.0.1', '2021-02-01 14:28:48,857 | INFO | Fetching package google-auth information from DB...
2021-02-01 14:28:48,857 | INFO | Initializing Package {'name': 'pipupgrade', 'version': '1.8.2', 'latest_version': '1.8.4', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,857 | INFO | Fetching package isort information from DB...
2021-02-01 14:28:48,856 | INFO | Fetching package google-auth-oauthlib information from DB...
2021-02-01 14:28:48,858 | INFO | Initializing Package {'name': 'pipx', 'version': '0.15.6.0', 'latest_version': '0.16.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,858 | INFO | Fetching package packaging information from DB...
    self.run()
2021-02-01 14:28:48,859 | INFO | Initializing Package {'name': 'protobuf', 'version': '3.9.2', 'latest_version': '3.14.02021-02-01 14:28:48,859 | INFO | Fetching package pipupgrade information from DB...
latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,859 | INFO | Initializing Package {'name': 'psutil', 'version': '5.7.3', 'latest_version': '5.8.0', 'latest_filetype': 'sdist'} of type <class 'dict'>...
2021-02-01 14:28:48,860 | INFO | Fetching package pipx information from DB...
2021-02-01 14:28:48,860 | INFO | Initializing Package {'name': 'rsa', 'version': '4.6', 'latest_version': '4.7', 'latest', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,860 | INFO | Initializing Package {'name': 'setuptools', 'version': '51.0.0', 'latest_version': '53.0.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
  File "c:\python310\lib\threading.py", line 910, in run
222_filetype': 'wheel'} of type <class 'dict'>...
2021-02-01 14:28:48,861 | INFO | Fetching package psutil information from DB...
2021-02-01 14:28:48,860 | INFO | Initializing Package {'name': 'urllib3', 'version': '1.24.2', 'latest_version': '1.26.3'2021-02-01 14:28:48,861 | INFO | Initializing Package {'name': 'userpath', 'version': '1.4.1', 'latest_version': '1.4.2'2021-02-01 14:28:48,862 | INFO | Fetching package setuptools information from DB...
021-02-01 14:28:48,859 | INFO | Initializing Package {'name': 'requests', 'version': '2.25.0', 'latest_version': '2.25.1021-02-01 14:28:48,861 | INFO | Initializing Package {'name': 'virtualenv', 'version': '20.2.2', 'latest_version': '20.4021-02-01 14:28:48,861 | INFO | Fetching package pip information from DB...
2    self._target(*self._args, **self._kwargs)
2021-02-01 14:28:48,863 | INFO | Fetching package rsa information from DB...
, 'latest_filetype': 'wheel'} of type <class 'dict'>...
, 'latest_filetype': 'wheel'} of type <class 'dict'>...
', 'latest_filetype': 'wheel'} of type <class 'dict'>...
.2', 'latest_filetype': 'wheel'} of type <class 'dict'>...
021-02-01 14:28:48,862 | INFO | Fetching package protobuf information from DB...
  File "c:\python310\lib\multiprocessing\pool.py", line 519, in _handle_workers
2021-02-01 14:28:48,867 | INFO | Fetching package urllib3 information from DB...
2021-02-01 14:28:48,867 | INFO | Fetching package userpath information from DB...
2021-02-01 14:28:48,868 | INFO | Fetching package requests information from DB...
2021-02-01 14:28:48,869 | INFO | Fetching package virtualenv information from DB...
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\python310\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python310\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66

```

**Comment by achillesrasquinha** [comment]
Hi Rashiq, this seems to be using maximum number of jobs that could lead to it turning exhaustive. Could you lower the number for the same? This has also been resolved in `1.8.4`.

**Comment by achillesrasquinha** [comment]
Closing this due to inactivity. Also fixed for 1.9.0

**Comment by RashiqAzhan** [comment]
I'm on version 1.9.0 and it still doesn't work. The terminal remains stuck indefinitely.

### Command used:
```
$ pipupgrade
```

### Terminal Output:
```
Checking...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
2021-03-26 08:44:37,274 | INFO | Fetching installed packages for C:\Python38\Scripts\pip.EXE...
2021-03-26 08:44:37,274 | INFO | Fetching installed packages for C:\Python38\Scripts\pip3.EXE...
    self.run()
2021-03-26 08:44:37,274 | INFO | Executing command: C:\Python38\Scripts\pip.EXE list --outdated --format json
  File "c:\python38\lib\threading.py", line 870, in run
2021-03-26 08:44:37,274 | INFO | Executing command: C:\Python38\Scripts\pip3.EXE list --outdated --format json
    self._target(*self._args, **self._kwargs)
  File "c:\python38\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\python38\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\python38\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python38\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
2021-03-26 08:44:39,004 | INFO | 1 packages found for C:\Python38\Scripts\pip.EXE.
2021-03-26 08:44:39,004 | INFO | 1 packages found for C:\Python38\Scripts\pip3.EXE.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python38\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\python38\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\python38\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python38\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python38\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
2021-03-26 08:44:40,724 | INFO | Initializing Package {'name': 'setuptools', 'version': '49.2.1', 'latest_version': '54.2.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...type': 'wheel'} of type <class 'dict'>...
2021-03-26 08:44:40,725 | INFO | Fetching package setuptools information from DB...
2021-03-26 08:44:40,728 | INFO | Using cached info for package <Package setuptools (49.2.1)>.
  File "c:\python38\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\python38\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\python38\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66                                                                          type': 'wheel'} of type <class 'dict'>...
2021-03-26 08:44:40,760 | INFO | Initializing Package {'name': 'setuptools', 'version': '49.2.1', 'latest_version': '54.2.0', 'latest_filetype': 'wheel'} of type <class 'dict'>...
2021-03-26 08:44:40,760 | INFO | Fetching package setuptools information from DB...
2021-03-26 08:44:40,764 | INFO | Using cached info for package <Package setuptools (49.2.1)>.
```

**Comment by achillesrasquinha** [comment]
I am unable to diagnose without specifiying `pipupgrade --verbose`. Could you share me that report please?
